name: PR
main: ExamplePlugin\MainClass
version: 1.0.0
api: [1.0.0]

load: POSTWORLD
author: PR
description: Example plugin showing the new API
commands:
 pr:
  description: PR Main Command
  usage: "Usage: /pr"
  permission: pr.command.main
permissions:
 exampleplugin.command.example:
  description: "Allows the user to run the example command"
  default: true
